namespace: storage
name: ibm
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:coll-test/storage.ibm.git
documentation: https://github.com/coll-test/storage.ibm/tree/master/docs
homepage: https://github.com/coll-test/storage.ibm
issues: https://github.com/coll-test/storage.ibm/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
